# Generated by Django 3.2.12 on 2023-11-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Rno',
            field=models.IntegerField(),
        ),
    ]
